<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DI8SEQA" name="test" tests="2" failures="1" timestamp="27 May 2023 20:29:04 GMT" time="60.662" errors="0">
  <testcase name="loginWithInvalidCridentiels" time="8.675" classname="test.TestLogin">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at test.TestLogin.loginWithInvalidCridentiels(TestLogin.java:63)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidCridentiels -->
  <testcase name="loginWithValidCridentiels" time="12.696" classname="test.TestLogin"/>
</testsuite> <!-- test -->
